default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  username: <%= Settings.database.development[:username] %>
  password: <%= Settings.database.development[:password] %>
  host: <%= Settings.database.development[:host] %>
  database: gtf

development_idcert:
  <<: *default
  username: <%= Settings.database.development[:username] %>
  password: <%= Settings.database.development[:password] %>
  host: <%= Settings.database.development[:host] %>
  database: idcert_dev

development_shared:
  <<: *default
  username: <%= Settings.database.development[:username] %>
  password: <%= Settings.database.development[:password] %>
  host: <%= Settings.database.development[:host] %>
  database: shared_dev

test:
  <<: *default
  username: <%= Settings.database.test[:username] %>
  password: <%= Settings.database.test[:password] %>
  host: <%= Settings.database.test[:host] %>
  database: gtf_test

test_idcert:
  <<: *default
  username: <%= Settings.database.test[:username] %>
  password: <%= Settings.database.test[:password] %>
  host: <%= Settings.database.test[:host] %>
  database: idcert_test

test_shared:
  <<: *default
  username: <%= Settings.database.test[:username] %>
  password: <%= Settings.database.test[:password] %>
  host: <%= Settings.database.test[:host] %>
  database: shared_test

production:
  <<: *default
  username: <%= Settings.database.production[:username] %>
  password: <%= Settings.database.production[:password] %>
  host: <%= Settings.database.production[:host] %>
  database: gtf_production

production_idcert:
  <<: *default
  username: <%= Settings.database.production[:username] %>
  password: <%= Settings.database.production[:password] %>
  host: <%= Settings.database.production[:host] %>
  database: idcert_production

production_shared:
  <<: *default
  username: <%= Settings.database.production[:username] %>
  password: <%= Settings.database.production[:password] %>
  host: <%= Settings.database.production[:host] %>
  database: shared_production
